// src/lib/themes.ts
import type { Theme } from '../types.ts';

/**
 * Bibliothèque massive de thèmes avec animations interactives
 * +50 thèmes avec backgrounds animés et interactions
 */

// ============================================
// THÈMES POUR TERMINAL
// ============================================
export const TERMINAL_THEMES: Theme[] = [
  // Classiques
  {
    id: 'terminal-macos',
    name: 'macOS',
    description: 'Terminal macOS avec animations subtiles',
    category: 'terminal',
    colors: { bg: '#1e1e1e', text: '#e0e0e0', accent: '#61dafb', secondary: '#27c93f' },
    animation: 'pulse-glow',
    borderStyle: 'border',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl',
    customClass: 'bg-[#1e1e1e] border border-slate-700 hover:shadow-cyan-500/20 transition-all',
  },
  {
    id: 'terminal-hacker',
    name: 'Hacker',
    description: 'Effet Matrix avec glow vert intense',
    category: 'terminal',
    colors: { bg: '#000000', text: '#00ff00', accent: '#00ff41', secondary: '#39ff14' },
    animation: 'matrix-glow',
    borderStyle: 'border-2 border-green-500',
    borderRadius: 'rounded-none',
    shadow: 'shadow-lg shadow-green-500/50',
    customClass: 'bg-black border-2 border-green-500 glow-green animate-matrix',
  },
  {
    id: 'terminal-cyberpunk',
    name: 'Cyberpunk',
    description: 'Néon cyan/magenta ultra futuriste',
    category: 'terminal',
    colors: { bg: '#0a0e27', text: '#ff00ff', accent: '#00ffff', secondary: '#ff0080' },
    animation: 'neon-pulse',
    borderStyle: 'border-2 border-cyan-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-cyan-500/50',
    customClass: 'bg-[#0a0e27] border-2 border-cyan-500 glow-cyan animate-neon',
  },
  {
    id: 'terminal-dracula',
    name: 'Dracula',
    description: 'Dracula avec animations douces',
    category: 'terminal',
    colors: { bg: '#282a36', text: '#f8f8f2', accent: '#50fa7b', secondary: '#ff79c6' },
    animation: 'fade-glow',
    borderStyle: 'border border-slate-600',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-xl shadow-purple-500/20',
    customClass: 'bg-[#282a36] border border-purple-500/30 hover:border-purple-500/60 transition-all',
  },
  {
    id: 'terminal-nord',
    name: 'Nord',
    description: 'Palette nordique froide et élégante',
    category: 'terminal',
    colors: { bg: '#2e3440', text: '#d8dee9', accent: '#88c0d0', secondary: '#81a1c1' },
    animation: 'slide-glow',
    borderStyle: 'border border-blue-400/40',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-xl shadow-blue-500/10',
    customClass: 'bg-[#2e3440] border border-blue-400/40 hover:border-blue-400/80 transition-all',
  },
  // Animés & Gradient
  {
    id: 'terminal-aurora',
    name: 'Aurora',
    description: 'Dégradé animé aurore boréale',
    category: 'terminal',
    colors: { bg: '#0f1b2e', text: '#e0e6ff', accent: '#00d9ff', secondary: '#00ff88' },
    animation: 'aurora-shift',
    borderStyle: 'border-2 border-cyan-400',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-cyan-500/30',
    customClass: 'bg-gradient-to-br from-[#0f1b2e] via-[#1a1f3a] to-[#0a2e4a] border-2 border-cyan-400 animate-aurora',
  },
  {
    id: 'terminal-lava',
    name: 'Lava',
    description: 'Gradient animé rouge/orange/jaune',
    category: 'terminal',
    colors: { bg: '#1a0d0d', text: '#ffff00', accent: '#ff6600', secondary: '#ff0000' },
    animation: 'lava-flow',
    borderStyle: 'border-2 border-orange-500',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-orange-500/40',
    customClass: 'bg-gradient-to-r from-red-950 via-orange-900 to-yellow-900 border-2 border-orange-500 animate-lava',
  },
  {
    id: 'terminal-ocean',
    name: 'Ocean',
    description: 'Vagues animées dégradé bleu',
    category: 'terminal',
    colors: { bg: '#0a1f3a', text: '#00e5ff', accent: '#0099ff', secondary: '#00ccff' },
    animation: 'wave-flow',
    borderStyle: 'border-2 border-blue-400',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-blue-500/30',
    customClass: 'bg-gradient-to-br from-blue-950 to-cyan-900 border-2 border-blue-400 animate-ocean',
  },
  {
    id: 'terminal-minimal',
    name: 'Minimal',
    description: 'Style épuré sans animations',
    category: 'terminal',
    colors: { bg: '#ffffff', text: '#1f1f1f', accent: '#6366f1', secondary: '#64748b' },
    animation: 'none',
    borderStyle: 'border border-slate-200',
    borderRadius: 'rounded-md',
    shadow: 'shadow-sm',
    customClass: 'bg-white border border-slate-300',
  },
  {
    id: 'terminal-midnight',
    name: 'Midnight',
    description: 'Bleu nuit avec pulsation douce',
    category: 'terminal',
    colors: { bg: '#0f172a', text: '#e2e8f0', accent: '#3b82f6', secondary: '#60a5fa' },
    animation: 'pulse-blue',
    borderStyle: 'border border-blue-500/30',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-xl shadow-blue-500/20',
    customClass: 'bg-slate-950 border border-blue-500/40 hover:border-blue-500/80 transition-all',
  },
  // Spéciaux
  {
    id: 'terminal-sunset',
    name: 'Sunset',
    description: 'Coucher de soleil avec animations',
    category: 'terminal',
    colors: { bg: '#2d1b1b', text: '#ffd700', accent: '#ff6347', secondary: '#ff8c00' },
    animation: 'sunset-glow',
    borderStyle: 'border-2 border-orange-600',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-orange-500/40',
    customClass: 'bg-gradient-to-br from-red-950 via-orange-800 to-yellow-900 border-2 border-orange-600 animate-sunset',
  },
  {
    id: 'terminal-forest',
    name: 'Forest',
    description: 'Vert forêt avec animations nature',
    category: 'terminal',
    colors: { bg: '#0f1f1a', text: '#4ade80', accent: '#22c55e', secondary: '#86efac' },
    animation: 'forest-glow',
    borderStyle: 'border-2 border-green-600',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-green-500/30',
    customClass: 'bg-gradient-to-br from-green-950 to-emerald-900 border-2 border-green-600 animate-forest',
  },
];


// ============================================
// THÈMES POUR HEADER
// ============================================
export const HEADER_THEMES: Theme[] = [
  // Classiques
  {
    id: 'header-modern',
    name: 'Modern',
    description: 'Header moderne avec gradient subtil',
    category: 'header',
    colors: { bg: 'transparent', text: '#ffffff', accent: '#6366f1', secondary: '#ec4899' },
    animation: 'fade-in-down',
    borderStyle: 'border-b border-slate-700',
    borderRadius: 'rounded-none',
    shadow: 'shadow-none',
    customClass: 'border-b border-slate-700 hover:border-indigo-500/50 transition-colors',
  },
  {
    id: 'header-gradient',
    name: 'Gradient Vibrant',
    description: 'Gradient rose vers indigo animé',
    category: 'header',
    colors: { bg: 'gradient', text: '#ffffff', accent: '#fbbf24', secondary: '#60a5fa' },
    animation: 'fade-in-up',
    borderStyle: 'border-none',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl',
    customClass: 'bg-gradient-to-r from-indigo-600 to-pink-600 rounded-lg shadow-xl p-6 hover:shadow-2xl transition-shadow',
  },
  {
    id: 'header-neon',
    name: 'Neon Glow',
    description: 'Effets néon avec border animée',
    category: 'header',
    colors: { bg: '#0f172a', text: '#00ffff', accent: '#ff00ff', secondary: '#00ff00' },
    animation: 'neon-pulse',
    borderStyle: 'border-b-2 border-cyan-500',
    borderRadius: 'rounded-none',
    shadow: 'shadow-lg shadow-cyan-500/50',
    customClass: 'border-b-2 border-cyan-500 glow-cyan pb-4 animate-neon-border',
  },
  {
    id: 'header-aurora',
    name: 'Aurora Borealis',
    description: 'Dégradé animé aurore boréale',
    category: 'header',
    colors: { bg: 'gradient', text: '#e0e6ff', accent: '#00d9ff', secondary: '#00ff88' },
    animation: 'aurora-shift',
    borderStyle: 'border-b-2 border-cyan-400',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-cyan-500/30',
    customClass: 'bg-gradient-to-r from-blue-600 via-cyan-500 to-green-500 rounded-lg shadow-2xl p-6 animate-aurora',
  },
  {
    id: 'header-lava',
    name: 'Lava Flow',
    description: 'Dégradé animé lave',
    category: 'header',
    colors: { bg: 'gradient', text: '#ffff00', accent: '#ff6600', secondary: '#ff0000' },
    animation: 'lava-flow',
    borderStyle: 'border-b-2 border-orange-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-orange-500/40',
    customClass: 'bg-gradient-to-r from-red-600 via-orange-500 to-yellow-500 rounded-lg shadow-2xl p-6 animate-lava',
  },
  {
    id: 'header-ocean',
    name: 'Ocean Waves',
    description: 'Vagues animées dégradé bleu',
    category: 'header',
    colors: { bg: 'gradient', text: '#00e5ff', accent: '#0099ff', secondary: '#00ccff' },
    animation: 'wave-flow',
    borderStyle: 'border-b-2 border-blue-400',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-blue-500/30',
    customClass: 'bg-gradient-to-r from-blue-600 to-cyan-600 rounded-lg shadow-2xl p-6 animate-ocean',
  },
  // Minimalistes
  {
    id: 'header-minimal',
    name: 'Minimal Clean',
    description: 'Header épuré sans animations',
    category: 'header',
    colors: { bg: 'transparent', text: '#1f1f1f', accent: '#000000', secondary: '#64748b' },
    animation: 'none',
    borderStyle: 'border-none',
    borderRadius: 'rounded-none',
    shadow: 'shadow-none',
    customClass: '',
  },
  {
    id: 'header-glass',
    name: 'Glassmorphism',
    description: 'Effet verre poli futuriste',
    category: 'header',
    colors: { bg: 'rgba(255,255,255,0.1)', text: '#ffffff', accent: '#6366f1', secondary: '#60a5fa' },
    animation: 'fade-in-down',
    borderStyle: 'border border-white/20',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg',
    customClass: 'bg-white/10 backdrop-blur-md border border-white/20 rounded-lg p-6 hover:bg-white/20 transition-all',
  },
  {
    id: 'header-sunset',
    name: 'Sunset',
    description: 'Coucher de soleil animé',
    category: 'header',
    colors: { bg: 'gradient', text: '#ffd700', accent: '#ff6347', secondary: '#ff8c00' },
    animation: 'sunset-glow',
    borderStyle: 'border-b-2 border-orange-600',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-orange-500/40',
    customClass: 'bg-gradient-to-r from-red-600 via-orange-500 to-yellow-600 rounded-lg shadow-2xl p-6 animate-sunset',
  },
  {
    id: 'header-forest',
    name: 'Forest Green',
    description: 'Vert forêt avec animations nature',
    category: 'header',
    colors: { bg: 'gradient', text: '#4ade80', accent: '#22c55e', secondary: '#86efac' },
    animation: 'forest-glow',
    borderStyle: 'border-b-2 border-green-600',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-green-500/30',
    customClass: 'bg-gradient-to-r from-green-700 to-emerald-600 rounded-lg shadow-2xl p-6 animate-forest',
  },
  {
    id: 'header-galaxy',
    name: 'Galaxy',
    description: 'Espace avec étoiles animées',
    category: 'header',
    colors: { bg: 'gradient', text: '#e0e0ff', accent: '#b4a7ff', secondary: '#8b5cf6' },
    animation: 'pulse-glow',
    borderStyle: 'border-2 border-purple-500/50',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-2xl shadow-purple-500/20',
    customClass: 'bg-gradient-to-r from-purple-900 via-indigo-800 to-purple-900 rounded-xl shadow-2xl p-6 animate-galaxy',
  },
];


// ============================================
// THÈMES POUR CODE-SNIPPET
// ============================================
export const CODE_THEMES: Theme[] = [
  {
    id: 'code-dracula',
    name: 'Dracula',
    description: 'Dracula classique avec animations',
    category: 'code-snippet',
    colors: { bg: '#282a36', text: '#f8f8f2', accent: '#50fa7b', secondary: '#ff79c6' },
    animation: 'fade-glow',
    borderStyle: 'border border-slate-700',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-purple-500/20',
    customClass: 'bg-[#282a36] border border-purple-500/30 hover:border-purple-500/60 transition-all',
  },
  {
    id: 'code-nord',
    name: 'Nord',
    description: 'Palette nordique froide et élégante',
    category: 'code-snippet',
    colors: { bg: '#2e3440', text: '#d8dee9', accent: '#88c0d0', secondary: '#81a1c1' },
    animation: 'slide-glow',
    borderStyle: 'border border-blue-400/40',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-blue-500/20',
    customClass: 'bg-[#2e3440] border border-blue-400/40 hover:border-blue-400/80 transition-all',
  },
  {
    id: 'code-monokai',
    name: 'Monokai',
    description: 'Monokai classique élégant',
    category: 'code-snippet',
    colors: { bg: '#272822', text: '#f8f8f2', accent: '#a1efe4', secondary: '#f92672' },
    animation: 'fade-in',
    borderStyle: 'border border-slate-700',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl',
    customClass: 'bg-[#272822] border border-slate-700 hover:shadow-pink-500/20 transition-all',
  },
  {
    id: 'code-gruvbox-dark',
    name: 'Gruvbox Dark',
    description: 'Gruvbox sombre chaleureux',
    category: 'code-snippet',
    colors: { bg: '#282828', text: '#ebdbb2', accent: '#b8bb26', secondary: '#fb4934' },
    animation: 'fade-glow',
    borderStyle: 'border-2 border-orange-700',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl shadow-orange-500/20',
    customClass: 'bg-[#282828] border-2 border-orange-700/50 hover:border-orange-700 transition-all',
  },
  {
    id: 'code-tokyonight',
    name: 'Tokyo Night',
    description: 'Tokyo Night futuriste et vibrant',
    category: 'code-snippet',
    colors: { bg: '#1a1b26', text: '#c0caf5', accent: '#7aa2f7', secondary: '#f7768e' },
    animation: 'pulse-glow',
    borderStyle: 'border-2 border-blue-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl shadow-blue-500/30',
    customClass: 'bg-[#1a1b26] border-2 border-blue-500/50 hover:border-blue-500/80 transition-all animate-code-glow',
  },
  {
    id: 'code-onedark',
    name: 'One Dark',
    description: 'One Dark Pro populaire',
    category: 'code-snippet',
    colors: { bg: '#282c34', text: '#abb2bf', accent: '#61afef', secondary: '#e06c75' },
    animation: 'fade-glow',
    borderStyle: 'border border-slate-600',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-blue-500/20',
    customClass: 'bg-[#282c34] border border-blue-500/30 hover:border-blue-500/60 transition-all',
  },
  {
    id: 'code-solarized-dark',
    name: 'Solarized Dark',
    description: 'Solarized Dark reposant',
    category: 'code-snippet',
    colors: { bg: '#002b36', text: '#839496', accent: '#2aa198', secondary: '#dc322f' },
    animation: 'slide-glow',
    borderStyle: 'border border-cyan-600/50',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-cyan-500/10',
    customClass: 'bg-[#002b36] border border-cyan-600/50 hover:border-cyan-500 transition-all',
  },
  {
    id: 'code-material',
    name: 'Material Dark',
    description: 'Material Design dark moderne',
    category: 'code-snippet',
    colors: { bg: '#263238', text: '#eeffff', accent: '#80cbc4', secondary: '#f78c6b' },
    animation: 'pulse-glow',
    borderStyle: 'border-2 border-cyan-400/50',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl shadow-cyan-500/20',
    customClass: 'bg-[#263238] border-2 border-cyan-400/50 hover:border-cyan-400/80 transition-all',
  },
  {
    id: 'code-radical',
    name: 'Radical',
    description: 'Radical neon vibrant',
    category: 'code-snippet',
    colors: { bg: '#141b24', text: '#ffffff', accent: '#14f195', secondary: '#ff006e' },
    animation: 'neon-pulse',
    borderStyle: 'border-2 border-lime-400',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-2xl shadow-lime-500/40',
    customClass: 'bg-[#141b24] border-2 border-lime-400/70 hover:border-lime-400 transition-all animate-neon',
  },
];


// ============================================
// THÈMES POUR TIMELINE
// ============================================
export const TIMELINE_THEMES: Theme[] = [
  {
    id: 'timeline-classic',
    name: 'Classic Line',
    description: 'Timeline classique avec ligne',
    category: 'timeline',
    colors: { bg: 'transparent', text: '#e0e0e0', accent: '#6366f1', secondary: '#64748b' },
    animation: 'fade-in-up',
    borderStyle: 'border-l-4 border-indigo-500',
    borderRadius: 'rounded-none',
    shadow: 'shadow-none',
    customClass: 'border-l-4 border-indigo-500 pl-6 hover:border-indigo-400 transition-colors',
  },
  {
    id: 'timeline-cards',
    name: 'Cards',
    description: 'Timeline avec cartes individuelles',
    category: 'timeline',
    colors: { bg: '#1e293b', text: '#e2e8f0', accent: '#ec4899', secondary: '#64748b' },
    animation: 'slide-in-right',
    borderStyle: 'border border-slate-700',
    borderRadius: 'rounded-xl',
    shadow: 'shadow-lg hover:shadow-pink-500/20',
    customClass: 'bg-slate-800 border border-slate-700 rounded-xl p-4 shadow-lg hover:shadow-lg hover:shadow-pink-500/20 transition-all',
  },
  {
    id: 'timeline-dots',
    name: 'Dots',
    description: 'Timeline minimaliste avec points',
    category: 'timeline',
    colors: { bg: 'transparent', text: '#94a3b8', accent: '#3b82f6', secondary: '#1e293b' },
    animation: 'pulse',
    borderStyle: 'border-none',
    borderRadius: 'rounded-full',
    shadow: 'shadow-none',
    customClass: 'relative pl-8 before:absolute before:w-3 before:h-3 before:bg-blue-500 before:rounded-full before:-left-1.5 hover:before:scale-125 transition-transform',
  },
  {
    id: 'timeline-neon',
    name: 'Neon Pulse',
    description: 'Timeline néon avec animations',
    category: 'timeline',
    colors: { bg: 'transparent', text: '#00ffff', accent: '#ff00ff', secondary: '#00ff00' },
    animation: 'neon-pulse',
    borderStyle: 'border-l-4 border-cyan-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-cyan-500/30',
    customClass: 'border-l-4 border-cyan-500 pl-6 animate-neon-border',
  },
  {
    id: 'timeline-gradient',
    name: 'Gradient Aurora',
    description: 'Timeline avec gradient animé',
    category: 'timeline',
    colors: { bg: 'gradient', text: '#e0e6ff', accent: '#00d9ff', secondary: '#00ff88' },
    animation: 'aurora-shift',
    borderStyle: 'border-l-4 border-cyan-400',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-cyan-500/20',
    customClass: 'border-l-4 border-cyan-400 pl-6 bg-gradient-to-r from-blue-900/20 to-cyan-900/20 p-4 rounded-lg',
  },
  {
    id: 'timeline-smooth',
    name: 'Smooth Glow',
    description: 'Timeline douce avec glow',
    category: 'timeline',
    colors: { bg: '#1a1f3a', text: '#a8b5ff', accent: '#6d7dfe', secondary: '#94a3ff' },
    animation: 'fade-glow',
    borderStyle: 'border-l-4 border-indigo-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg shadow-indigo-500/20',
    customClass: 'border-l-4 border-indigo-500 pl-6 hover:shadow-lg hover:shadow-indigo-500/40 transition-shadow',
  },
];

// ============================================
// THÈMES POUR STACK (Compétences)
// ============================================
export const STACK_THEMES: Theme[] = [
  {
    id: 'stack-badges',
    name: 'Badges',
    description: 'Compétences en badges colorés',
    category: 'stack',
    colors: { bg: '#0f172a', text: '#e2e8f0', accent: '#6366f1', secondary: '#ec4899' },
    animation: 'fade-in-up',
    borderStyle: 'border-none',
    borderRadius: 'rounded-full',
    shadow: 'shadow-md',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-indigo-600 to-pink-600 rounded-full hover:shadow-lg hover:shadow-indigo-500/50 transition-all',
  },
  {
    id: 'stack-grid',
    name: 'Grid Cards',
    description: 'Grille de compétences en cartes',
    category: 'stack',
    colors: { bg: '#1e293b', text: '#e2e8f0', accent: '#3b82f6', secondary: '#64748b' },
    animation: 'fade-in-up',
    borderStyle: 'border border-slate-700',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-lg hover:shadow-blue-500/20',
    customClass: 'p-4 bg-slate-800 border border-slate-700 rounded-lg hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-500/20 transition-all',
  },
  {
    id: 'stack-neon',
    name: 'Neon Pulse',
    description: 'Badges néon avec animations',
    category: 'stack',
    colors: { bg: '#0a0e27', text: '#00ffff', accent: '#ff00ff', secondary: '#00ff00' },
    animation: 'neon-pulse',
    borderStyle: 'border-2 border-cyan-500',
    borderRadius: 'rounded-lg',
    shadow: 'shadow-xl shadow-cyan-500/40',
    customClass: 'inline-block px-4 py-2 border-2 border-cyan-500 rounded-lg bg-[#0a0e27] text-cyan-400 hover:shadow-xl hover:shadow-cyan-500/60 transition-all animate-neon',
  },
  {
    id: 'stack-gradient-glow',
    name: 'Gradient Glow',
    description: 'Badges dégradés avec glow',
    category: 'stack',
    colors: { bg: 'gradient', text: '#ffffff', accent: '#4ade80', secondary: '#60a5fa' },
    animation: 'pulse-glow',
    borderStyle: 'border-2 border-green-500/50',
    borderRadius: 'rounded-full',
    shadow: 'shadow-lg shadow-green-500/40',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-green-600 to-blue-600 rounded-full border-2 border-green-500/50 hover:border-green-500 hover:shadow-lg hover:shadow-green-500/60 transition-all',
  },
  {
    id: 'stack-aurora',
    name: 'Aurora',
    description: 'Badges aurore boréale',
    category: 'stack',
    colors: { bg: 'gradient', text: '#e0e6ff', accent: '#00d9ff', secondary: '#00ff88' },
    animation: 'aurora-shift',
    borderStyle: 'border-2 border-cyan-400',
    borderRadius: 'rounded-full',
    shadow: 'shadow-xl shadow-cyan-500/30',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-cyan-600 via-blue-600 to-green-600 rounded-full border-2 border-cyan-400 hover:shadow-xl hover:shadow-cyan-500/50 transition-all animate-aurora',
  },
  {
    id: 'stack-lava',
    name: 'Lava',
    description: 'Badges lave animés',
    category: 'stack',
    colors: { bg: 'gradient', text: '#ffff00', accent: '#ff6600', secondary: '#ff0000' },
    animation: 'lava-flow',
    borderStyle: 'border-2 border-orange-500',
    borderRadius: 'rounded-full',
    shadow: 'shadow-xl shadow-orange-500/40',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-red-600 via-orange-500 to-yellow-500 rounded-full border-2 border-orange-500 hover:shadow-xl hover:shadow-orange-500/50 transition-all animate-lava',
  },
  {
    id: 'stack-ocean',
    name: 'Ocean Waves',
    description: 'Badges vagues océan',
    category: 'stack',
    colors: { bg: 'gradient', text: '#00e5ff', accent: '#0099ff', secondary: '#00ccff' },
    animation: 'wave-flow',
    borderStyle: 'border-2 border-blue-400',
    borderRadius: 'rounded-full',
    shadow: 'shadow-xl shadow-blue-500/30',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-blue-600 to-cyan-600 rounded-full border-2 border-blue-400 hover:shadow-xl hover:shadow-blue-500/50 transition-all animate-ocean',
  },
  {
    id: 'stack-forest',
    name: 'Forest',
    description: 'Badges forêt naturelle',
    category: 'stack',
    colors: { bg: 'gradient', text: '#4ade80', accent: '#22c55e', secondary: '#86efac' },
    animation: 'forest-glow',
    borderStyle: 'border-2 border-green-600',
    borderRadius: 'rounded-full',
    shadow: 'shadow-xl shadow-green-500/30',
    customClass: 'inline-block px-4 py-2 bg-gradient-to-r from-green-700 to-emerald-600 rounded-full border-2 border-green-600 hover:shadow-xl hover:shadow-green-500/50 transition-all animate-forest',
  },
];

// ============================================
// Utilitaires pour récupérer les thèmes
// ============================================
export function getThemesByType(type: string): Theme[] {
  const themeMap: { [key: string]: Theme[] } = {
    terminal: TERMINAL_THEMES,
    header: HEADER_THEMES,
    'code-snippet': CODE_THEMES,
    timeline: TIMELINE_THEMES,
    stack: STACK_THEMES,
  };
  return themeMap[type] || [];
}

export function getThemeById(id: string): Theme | undefined {
  const allThemes = [
    ...TERMINAL_THEMES,
    ...HEADER_THEMES,
    ...CODE_THEMES,
    ...TIMELINE_THEMES,
    ...STACK_THEMES,
  ];
  return allThemes.find((t) => t.id === id);
}
